name: Domains

on:
    pull_request:
        paths:
            - "domains/**"

jobs:
    validate_email:
        name: Validate Email
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Find Modified JSON Files
              id: find_files
              run: |
                  echo "::set-output name=files::$(git diff --name-only --diff-filter=M | grep '\.json$' || echo '')"

            - name: Retrieve and Validate Emails
              id: validate_email
              run: |
                  for file in ${{ steps.find_files.outputs.files }}; do
                      owner_email=$(jq -r '.owner.email' "$file")
                      echo "Validating email: $owner_email"
                      echo "::set-output name=email::$owner_email"
                  done

            - name: Validate Email
              id: email_validation
              run: |
                  failed_validations=""

                  for file in ${{ steps.find_files.outputs.files }}; do
                      owner_email=$(jq -r '.owner.email' "$file")
                      echo "Validating email: $owner_email"

                      if ! email_validation_result=$(wdhdev/email-validator@main --email "$owner_email"); then
                          echo "${file} failed email validation."
                          failed_validations="${failed_validations}${file}\n"
                      fi
                  done

                  if [ -n "$failed_validations" ]; then
                      echo "::error:: Email validation failed for the following files:\n${failed_validations}"
                      exit 1
                  fi
