name: Validation

on:
    pull_request:

    push:
        branches: [main]
        paths:
            - "domains/**"
            - ".github/workflows/validation.yml"
            - "scripts/dns.js"

    workflow_dispatch:

concurrency:
    group: ${{ github.ref }}-validation
    cancel-in-progress: true

jobs:
    dns:
        name: DNS
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: DNSControl Check
              uses: koenrh/dnscontrol-action@v3
              with:
                  args: check
                  config_file: "scripts/dns.js"

    emails:
        name: Emails
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Find Files
              id: find_files
              run: |
                  if [[ "${{ github.event_name }}" == "pull_request" ]]; then
                      files=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                          "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files?per_page=100" \
                          | jq -r '.[] | select(.status == "added" or .status == "modified") | .filename' \
                          | grep '^domains/[^/]*\.json$')
                  else
                      files=$(git diff --name-only --diff-filter=AM "domains/" | grep '\.json$' || echo '')
                  fi

                  echo "::set-output name=files::${files}"

            - name: Validate Emails
              run: |
                  for file in ${{ steps.find_files.outputs.files }}; do
                      filename=$(basename "$file")
                      email=$(jq -r '.owner.email' "$file")

                      echo "Validating $email in $filename"

                      result=$(node scripts/validate-email/dist/index.js --email "$email")
                      echo "Raw response: $result"

                      fixed_result=$(echo "$result" | jq -R -s -c 'split("\n")')

                      success=$(echo "$fixed_result" | jq -r '.success')

                      if [[ "$success" == "false" ]]; then
                          echo "::error::FAIL $email $filename"
                          echo "FAIL $email $filename" >> failed_validations.txt
                      else
                          echo "PASS $email $filename"
                      fi
                  done

                  if [[ -s failed_validations.txt ]]; then
                      exit 1
                  fi

    json:
        name: JSON
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: JSON Syntax Check
              uses: limitusus/json-syntax-check@v1
              with:
                  pattern: "\\.json$"
              env:
                  BASE: "domains/"
